name: Publish

on:
  push:
    branches:
      - master  # أو main حسب اسم الفرع الأساسي.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # حدّث إلى إصدار .NET الذي تستخدمه.

    - name: Authenticate with GitHub Packages
      run: |
        dotnet nuget add source \
          --username ${{ secrets.NAMESECRET }} \
          --password ${{ secrets.SECRETTOKEN }} \
          --store-password-in-clear-text \
          --name github \
          https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release  # يضمن بناء المشروع في وضع الإصدار.

    - name: Build and Pack
      run: dotnet pack --configuration Release --output ./bin/Release  # مجلد مخرجات محدد.

    - name: Verify Files
      run: ls -al ./bin/Release  # عرض قائمة الملفات لتأكيد وجود ملفات .nupkg.

    - name: Publish Package to GitHub Packages
      run: dotnet nuget push ./bin/Release/*.nupkg --source github
